# Generated by Django 3.2 on 2021-07-17 02:36

import BICON_App.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_logo', models.ImageField(upload_to='logo', validators=[BICON_App.validators.validate_file_size], verbose_name='')),
                ('college_name', models.TextField()),
                ('address', models.TextField()),
                ('building_image', models.ImageField(upload_to='building', validators=[BICON_App.validators.validate_file_size], verbose_name='')),
                ('establishment_year', models.IntegerField()),
                ('campus_area', models.IntegerField(default=0)),
                ('branches', models.TextField(default='Not Available')),
            ],
        ),
    ]
