# Generated by Django 3.2 on 2021-07-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BICON_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('Category_id', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('Category', models.CharField(default='-', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('Round_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Round', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('Year_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Year', models.IntegerField(default=0)),
            ],
        ),
    ]
