# Generated by Django 3.2 on 2021-07-17 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BICON_App', '0002_categories_rounds_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CSE1', models.CharField(default='-', max_length=15)),
                ('CSE2', models.CharField(default='-', max_length=15)),
                ('CSE3', models.CharField(default='-', max_length=15)),
                ('CSE4', models.CharField(default='-', max_length=15)),
                ('EEE1', models.CharField(default='-', max_length=15)),
                ('EEE2', models.CharField(default='-', max_length=15)),
                ('EEE3', models.CharField(default='-', max_length=15)),
                ('EEE4', models.CharField(default='-', max_length=15)),
                ('ECE1', models.CharField(default='-', max_length=15)),
                ('ECE2', models.CharField(default='-', max_length=15)),
                ('ECE3', models.CharField(default='-', max_length=15)),
                ('ECE4', models.CharField(default='-', max_length=15)),
                ('EE1', models.CharField(default='-', max_length=15)),
                ('EE2', models.CharField(default='-', max_length=15)),
                ('EE3', models.CharField(default='-', max_length=15)),
                ('EE4', models.CharField(default='-', max_length=15)),
                ('ME1', models.CharField(default='-', max_length=15)),
                ('ME2', models.CharField(default='-', max_length=15)),
                ('ME3', models.CharField(default='-', max_length=15)),
                ('ME4', models.CharField(default='-', max_length=15)),
                ('CE1', models.CharField(default='-', max_length=15)),
                ('CE2', models.CharField(default='-', max_length=15)),
                ('CE3', models.CharField(default='-', max_length=15)),
                ('CE4', models.CharField(default='-', max_length=15)),
                ('Category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BICON_App.categories')),
                ('Round', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BICON_App.rounds')),
                ('Year', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BICON_App.years')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BICON_App.colleges')),
            ],
            options={
                'db_table': 'BICON_App_cutoff',
            },
        ),
        migrations.CreateModel(
            name='branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=5)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collegeId', related_query_name='collegeId', to='BICON_App.colleges')),
            ],
        ),
    ]
