# Generated by Django 3.2 on 2021-07-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BICON_App', '0004_auto_20210717_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cutoff',
            old_name='college_id',
            new_name='college',
        ),
    ]
