# Generated by Django 3.2 on 2021-08-13 07:25

import BICON_App.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BICON_App', '0005_rename_college_id_cutoff_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='data_contributors', validators=[BICON_App.validators.validate_file_size], verbose_name='')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=5)),
                ('year', models.IntegerField(default=0)),
                ('college', models.CharField(max_length=30)),
            ],
        ),
    ]
