# Generated by Django 3.2 on 2021-09-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BICON_App', '0008_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='response',
            field=models.CharField(default='', max_length=500),
        ),
    ]
